### ISSUE TITLE
Still using proxy after turning the proxy "off"

### ISSUE THREAD

**Issue by EnderBlue** [mohamedmansour/proxy-anywhere-extension#4]
When I click the icon to turn the proxy off, it still seems to try and route through the proxy.

**Comment by mohamedmansour** [comment]
Hi EnderBlue, what version are you running?

**Comment by EnderBlue** [comment]
Version 0.3

**Comment by mohamedmansour** [comment]
What version of Google Chrome are you using?

**Comment by EnderBlue** [comment]
12.0.712.0
